apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ekscluster
  region: ap-south-1

managedNodeGroups:
  - name: spot
    spot: true
    instanceType: m5.large
    desiredCapacity: 3
    availabilityZones:
      - ap-south-1a
    ssh:
      publicKeyName: last
